DROP TABLE IF EXISTS ENSEIGNANT ;
CREATE TABLE ENSEIGNANT (NOM_ENSEIGNANT CHAR(30) ,
PRENOM_ENSEIGNANT CHAR(30),
PRIMARY KEY (NOM_ENSEIGNANT)) ENGINE=InnoDB;

DROP TABLE IF EXISTS COUR ;
CREATE TABLE COUR (MATIERE_COUR CHAR(20) ,
NOM_ENSEIGNANT CHAR(20),
NOM_SALLE CHAR(20),
PRIMARY KEY (MATIERE_COUR)) ENGINE=InnoDB;

DROP TABLE IF EXISTS ELEVE ;
CREATE TABLE ELEVE (NOM_Eleve CHAR(30) ,
PRENOM_Eleve CHAR(30),
FONDATION_Classe CHAR(30),
PRIMARY KEY (NOM_Eleve)) ENGINE=InnoDB;

DROP TABLE IF EXISTS TRANCHE_HORAIRE ;
CREATE TABLE TRANCHE_HORAIRE (DATE_DEBUT CHAR ,
DATE_FIN CHAR,
PRIMARY KEY (DATE_DEBUT)) ENGINE=InnoDB;

DROP TABLE IF EXISTS CLASSE ;
CREATE TABLE CLASSE (FONDATION_Classe CHAR,
NIVEAU_Classe CHAR,
PRIMARY KEY (FONDATION_Classe)) ENGINE=InnoDB;

DROP TABLE IF EXISTS SALLE ;
CREATE TABLE SALLE (NOM_SALLE CHAR(20) ,
LOGO_SALLE CHAR(20),
PRIMARY KEY (NOM_SALLE)) ENGINE=InnoDB;

DROP TABLE IF EXISTS ENSEIGNER ;
CREATE TABLE ENSEIGNER (NOM_ENSEIGNANT CHAR(30) ,
MATIERE_COUR CHAR(30) NOT NULL,
PRIMARY KEY (NOM_ENSEIGNANT,
 MATIERE_COUR)) ENGINE=InnoDB;

DROP TABLE IF EXISTS OCCUPER ;
CREATE TABLE OCCUPER (MATIERE_COUR CHAR(20) ,
DATE_DEBUT CHAR(20) NOT NULL,
PRIMARY KEY (MATIERE_COUR,
 DATE_DEBUT)) ENGINE=InnoDB;

DROP TABLE IF EXISTS ASSISTER ;
CREATE TABLE ASSISTER (MATIERE_COUR CHAR(20) ,
NOM_Eleve CHAR(20) NOT NULL,
PRIMARY KEY (MATIERE_COUR,
 NOM_Eleve)) ENGINE=InnoDB;

